apiVersion: v1
kind: ServiceAccount
metadata:
  name: treasuryuat
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: treasuryuat
  namespace: default
  labels:
    app: treasuryuat
    service: treasuryuat
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: treasuryuat
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: treasuryuat
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treasuryuat
      version: v1
  template:
    metadata:
      labels:
        app: treasuryuat
        version: v1
    spec:
      serviceAccountName: treasuryuat
      containers:
      - image: IMAGE
        imagePullPolicy: Always
        name: treasuryuat
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: docker-registry-creds
---

